#!/usr/bin/env python
# -*- coding: utf-8 -*-

from jobs.models import Job
from companies.models import Company
from django.contrib.auth.models import Group
from fairs.models import Fair
from users.models import User

JOB_TYPES_LIST = (
	('Engineering Software', 'Engineering Software'),
	('Engineering Hardware', 'Engineering Hardware'),
	('Product/Project Management', 'Product/Project Management'),
	('Engineering QA', 'Engineering QA'),
	('WebDev/Design/Internet', 'WebDev/Design/Internet'),
	('Tech Ops/Data', 'Tech Ops/Data'),
	('Technical/Customer Support', 'Technical/Customer Support'),
	('Manufacturing', 'Manufacturing'),
	('Life Sciences', 'Life Sciences'),
	('Marketing/PR/Product Mktg', 'Marketing/PR/Product Mktg'),
	('Sales','Sales'),
	('Business Dev', 'Business Dev'),
	('Professional Svcs', 'Professional Svcs'),
	('Accounting/Finance', 'Accounting/Finance'),
	('HR/Recruiting','HR/Recruiting'),
	('Administration', 'Administration'),
	('Legal', 'Legal'),
	('Operations', 'Operations'),
	('Other','Other'),
	)

new_job = Job(name='Engineering Intern', description='', job_type='Engineering QA', company=Company.objects.get(id=605), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Quality Intern', description='', job_type='Engineering QA', company=Company.objects.get(id=605), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Environmental Health and Safety Intern', description='', job_type='Engineering QA', company=Company.objects.get(id=605), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Data and Policy Analyst-Statistical Programmer', description='', job_type='Engineering Software', company=Company.objects.get(id=350), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Data and Policy Analyst-Writer/Coordinator', description='', job_type='Other', company=Company.objects.get(id=350), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Data Systems Programmer', description='', job_type='Engineering Software', company=Company.objects.get(id=350), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software and Web Developer', description='', job_type='Engineering Software', company=Company.objects.get(id=350), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Interaction Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=211), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Visual Designer', description='', job_type='Engineering Software', company=Company.objects.get(id=211), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Usability Professional', description='', job_type='Engineering QA', company=Company.objects.get(id=211), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Development QA Intern', description='', job_type='Engineering QA', company=Company.objects.get(id=211), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='System Software Engineer - Summer Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=211), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Web Experience', description='', job_type='Engineering Software', company=Company.objects.get(id=211), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Data Visualization Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=211), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='User Experience Design Internship', description='', job_type='Engineering QA', company=Company.objects.get(id=211), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Sales Analyst Summer Intern', description='', job_type='Sales', company=Company.objects.get(id=211), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=590), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Bioinformatics', description='', job_type='Life Sciences', company=Company.objects.get(id=590), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Frontend Developer Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=588), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=215), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Hardware Engineer', description='', job_type='Engineering Hardware', company=Company.objects.get(id=215), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Platforms Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=215), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Embedded and Software Engineer/Summer Interns', description='', job_type='Engineering Software', company=Company.objects.get(id=614), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Marketing Interns', description='', job_type='Marketing/PR/Product Mktg', company=Company.objects.get(id=614), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer - Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=218), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer- New Grad', description='', job_type='Engineering Software', company=Company.objects.get(id=218), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Bay Area SMACNA Intern', description='', job_type='Other', company=Company.objects.get(id=613), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Construction Management', description='', job_type='Product/Project Management', company=Company.objects.get(id=221), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Civil Engineering (Masters)', description='', job_type='Tech Ops/Data', company=Company.objects.get(id=221), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Mechanical/Electrical Engineering', description='', job_type='Tech Ops/Data', company=Company.objects.get(id=221), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern - R&D Engineering', description='', job_type='Engineering Software', company=Company.objects.get(id=618), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern - Engineering', description='', job_type='Engineering Software', company=Company.objects.get(id=618), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern - Marketing Specialist', description='', job_type='Marketing/PR/Product Mktg', company=Company.objects.get(id=618), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern - Web Marketing', description='', job_type='Marketing/PR/Product Mktg', company=Company.objects.get(id=618), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern - Business Analyst', description='', job_type='Business Dev', company=Company.objects.get(id=618), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern - Product Manager', description='', job_type='Product/Project Management', company=Company.objects.get(id=618), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Summer Internship', description='', job_type='Engineering Software', company=Company.objects.get(id=478), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Various Summer Intern and New Grad Openings.', description='', job_type='Other', company=Company.objects.get(id=244), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineering Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=606), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Product Intern', description='', job_type='Product/Project Management', company=Company.objects.get(id=606), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Network Marketing Intern', description='', job_type='Marketing/PR/Product Mktg', company=Company.objects.get(id=606), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Communications Intern', description='', job_type='Marketing/PR/Product Mktg', company=Company.objects.get(id=606), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Business Intelligence Intern', description='', job_type='Business Dev', company=Company.objects.get(id=606), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=603), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software I Engineer (Intern) - Engineering', description='', job_type='Engineering Software', company=Company.objects.get(id=247), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Development Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=607), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Marketing Intern', description='', job_type='Marketing/PR/Product Mktg', company=Company.objects.get(id=607), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Product Management Intern', description='', job_type='Product/Project Management', company=Company.objects.get(id=607), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Graphic Designer', description='', job_type='Other', company=Company.objects.get(id=608), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Business Analyst', description='', job_type='Business Dev', company=Company.objects.get(id=608), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=608), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Quality Assurance Analyst', description='', job_type='Engineering QA', company=Company.objects.get(id=608), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Web Developer', description='', job_type='Engineering Software', company=Company.objects.get(id=608), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='UX Analyst/Designer', description='', job_type='Engineering Software', company=Company.objects.get(id=608), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineering Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=250), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineering', description='', job_type='Engineering Software', company=Company.objects.get(id=250), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Web Development FT & Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=565), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Web Design FT & Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=565), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Marketing FT & Intern', description='', job_type='Marketing/PR/Product Mktg', company=Company.objects.get(id=565), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Quantitative Analyst (full-time and internship)', description='', job_type='Other', company=Company.objects.get(id=579), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Developer (full-time and internship)', description='', job_type='Engineering Software', company=Company.objects.get(id=579), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Junior Proprietary Trader (full-time and internship)', description='', job_type='Other', company=Company.objects.get(id=579), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Corporate Development (full-time and internship)', description='', job_type='Business Dev', company=Company.objects.get(id=579), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software QA', description='', job_type='Engineering QA', company=Company.objects.get(id=251), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='On-Line Marketing Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=602), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Content Editor Intern', description='', job_type='Other', company=Company.objects.get(id=602), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Mobile Engineer Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=602), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='QA Intern', description='', job_type='Engineering QA', company=Company.objects.get(id=602), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Finance Intern', description='', job_type='Accounting/Finance', company=Company.objects.get(id=602), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Product Management Intern', description='', job_type='Product/Project Management', company=Company.objects.get(id=602), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Biochemistry', description='', job_type='Other', company=Company.objects.get(id=472), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Molecular Biology', description='', job_type='Other', company=Company.objects.get(id=472), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Chemical Engineering', description='', job_type='Other', company=Company.objects.get(id=472), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Chemistry Internship', description='', job_type='Other', company=Company.objects.get(id=457), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer - Front End', description='', job_type='Engineering Software', company=Company.objects.get(id=480), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer - Back End', description='', job_type='Engineering Software', company=Company.objects.get(id=480), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Engineer Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=584), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Beta/ Customer Service Intern', description='', job_type='Other', company=Company.objects.get(id=584), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='QA Intern', description='', job_type='Engineering QA', company=Company.objects.get(id=584), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern Technical', description='', job_type='Engineering Software', company=Company.objects.get(id=593), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer Internship/Co-Op', description='', job_type='Engineering Software', company=Company.objects.get(id=259), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=259), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Assistant Instructor', description='', job_type='Other', company=Company.objects.get(id=615), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Team Leader', description='', job_type='Other', company=Company.objects.get(id=615), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Lead Instructor', description='', job_type='Other', company=Company.objects.get(id=615), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Summer Internship opportunities within different business functions.', description='', job_type='Business Dev', company=Company.objects.get(id=625), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Engineering', description='', job_type='Other', company=Company.objects.get(id=261), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Internship - Software Development', description='', job_type='Engineering Software', company=Company.objects.get(id=263), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer, Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=596), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='ASIC Engineers', description='', job_type='Engineering Hardware', company=Company.objects.get(id=601), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='SSD Firmware Engineers', description='', job_type='Engineering Hardware', company=Company.objects.get(id=601), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='HDD Firmware Engineers', description='', job_type='Engineering Hardware', company=Company.objects.get(id=601), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Flash Technology Developers', description='', job_type='Engineering Hardware', company=Company.objects.get(id=601), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Developers', description='', job_type='Engineering Software', company=Company.objects.get(id=601), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Mechanical Engineers', description='', job_type='Engineering Hardware', company=Company.objects.get(id=601), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Protoyping Engineers', description='', job_type='Engineering Hardware', company=Company.objects.get(id=601), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='SoC Engineers', description='', job_type='Engineering Hardware', company=Company.objects.get(id=601), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Firmware Test and Tools Engineer', description='', job_type='Engineering QA', company=Company.objects.get(id=601), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Strorage Architecture', description='', job_type='Engineering Hardware', company=Company.objects.get(id=601), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Research and Development', description='', job_type='Engineering Hardware', company=Company.objects.get(id=601), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Developers and Software Testers - Entry Level and Intern Opportunities', description='', job_type='Engineering Software', company=Company.objects.get(id=269), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer Entry Level', description='', job_type='Engineering Software', company=Company.objects.get(id=270), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer Summer Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=270), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Analytics Engineer New Grad', description='', job_type='Engineering Software', company=Company.objects.get(id=270), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Analytics Engineer Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=270), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Customer Happiness Agent', description='', job_type='Other', company=Company.objects.get(id=270), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Development Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=496), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Development Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=496), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer - Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=273), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer-New Grad', description='', job_type='Engineering Software', company=Company.objects.get(id=273), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer (All positions)', description='', job_type='Engineering Software', company=Company.objects.get(id=273), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Product Analyst-Language Arts', description='', job_type='Other', company=Company.objects.get(id=273), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Product Analyst-Math', description='', job_type='Other', company=Company.objects.get(id=273), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Product Analyst-Science', description='', job_type='Other', company=Company.objects.get(id=273), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Product Analyst-Social ', description='', job_type='Other', company=Company.objects.get(id=273), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Engineering Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=620), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software developer', description='', job_type='Engineering Software', company=Company.objects.get(id=569), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Front-end Engineer Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=569), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='2014 Technology Summer Analyst Program - NY Metro', description='', job_type='Engineering Software', company=Company.objects.get(id=573), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Chemical Engineer Intern', description='', job_type='Other', company=Company.objects.get(id=581), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Materials Science Engineer Intern', description='', job_type='Other', company=Company.objects.get(id=581), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Life Science Engineer Intern', description='', job_type='Life Sciences', company=Company.objects.get(id=581), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Accounting Intern', description='', job_type='Accounting/Finance', company=Company.objects.get(id=581), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern: Software Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=274), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern: System Test Engineer', description='', job_type='Engineering QA', company=Company.objects.get(id=274), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern: Web Developer', description='', job_type='Engineering Software', company=Company.objects.get(id=274), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern: Marketing Coordinator', description='', job_type='Marketing/PR/Product Mktg', company=Company.objects.get(id=274), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern: Software Developer', description='', job_type='Engineering Software', company=Company.objects.get(id=274), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='IT- Software Engineering Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=464), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern-Tech', description='', job_type='Engineering Software', company=Company.objects.get(id=497), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern Non-Tech', description='', job_type='Other', company=Company.objects.get(id=497), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Summer Internships Available', description='', job_type='Other', company=Company.objects.get(id=599), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Senior Rails Developer', description='', job_type='Engineering Software', company=Company.objects.get(id=589), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Senior Sofware Developer', description='', job_type='Engineering Software', company=Company.objects.get(id=589), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Developer', description='', job_type='Engineering Software', company=Company.objects.get(id=589), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Operations Research Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=589), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Mobile Application Developer', description='', job_type='Engineering Software', company=Company.objects.get(id=589), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='User Experience/Interaction Designer', description='', job_type='Engineering Software', company=Company.objects.get(id=589), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Quality Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=589), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Server Operations Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=589), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Developer Internships', description='', job_type='Engineering Software', company=Company.objects.get(id=589), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Design Engineering Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=622), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Four Star Generalist Software Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=342), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Glass Half Full-Stack Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=342), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name="I'll Be Back-End Data Engineer", description='', job_type='Engineering Software', company=Company.objects.get(id=342), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Product Manager - Customer Implementation', description='', job_type='Product/Project Management', company=Company.objects.get(id=342), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Statistically Significant Data Scientist', description='', job_type='Engineering Software', company=Company.objects.get(id=342), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='public static final intern softwareEngineer = fall/winter/spring', description='', job_type='Engineering Software', company=Company.objects.get(id=342), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Non-Tech Summer Internship', description='', job_type='Other', company=Company.objects.get(id=279), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Technology Summer Internship', description='', job_type='Engineering Software', company=Company.objects.get(id=279), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Junior Developer', description='', job_type='Engineering Software', company=Company.objects.get(id=315), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Developer Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=315), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Remote Support Tutor', description='', job_type='Other', company=Company.objects.get(id=315), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Marketing', description='', job_type='Marketing/PR/Product Mktg', company=Company.objects.get(id=315), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Support', description='', job_type='Other', company=Company.objects.get(id=315), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer Internship', description='', job_type='Engineering Software', company=Company.objects.get(id=578), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineering Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=369), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineering', description='', job_type='Engineering Software', company=Company.objects.get(id=369), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer (Full Time)', description='', job_type='Engineering Software', company=Company.objects.get(id=246), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer (Intern)', description='', job_type='Engineering Software', company=Company.objects.get(id=246), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=471), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Engineering Interns', description='', job_type='Engineering Software', company=Company.objects.get(id=597), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Pathways Intern (various)', description='', job_type='Engineering Software', company=Company.objects.get(id=598), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Full-time and Internships: Eng (HW, SW, Web Services, Algorithms, Integration Engineering, Apps Development, DevOps, Design, Engineering Program Management, etc.)', description='', job_type='Engineering Software', company=Company.objects.get(id=346), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Full-time and Internships: Sales, Marketing, Program Management, Business Development, Operations, Finance and HR.', description='', job_type='Other', company=Company.objects.get(id=346), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer Interns', description='', job_type='Engineering Software', company=Company.objects.get(id=604), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern, Marketing', description='', job_type='Marketing/PR/Product Mktg', company=Company.objects.get(id=440), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern, Customer Support', description='', job_type='Other', company=Company.objects.get(id=440), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern, Software Engineering', description='', job_type='Engineering Software', company=Company.objects.get(id=440), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Internship, Engineering', description='', job_type='Engineering Software', company=Company.objects.get(id=591), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Internship, Marketing', description='', job_type='Marketing/PR/Product Mktg', company=Company.objects.get(id=591), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Internship, Sales', description='', job_type='Other', company=Company.objects.get(id=591), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Firmware Engineer Intern', description='', job_type='Engineering Hardware', company=Company.objects.get(id=612), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Research Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=612), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=612), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='EE Intern', description='', job_type='Engineering Hardware', company=Company.objects.get(id=612), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='ME Intern', description='', job_type='Other', company=Company.objects.get(id=612), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Volunteer Overseas Positions', description='', job_type='Other', company=Company.objects.get(id=511), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=485), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Designer', description='', job_type='Engineering Software', company=Company.objects.get(id=485), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Biz Ops', description='', job_type='Business Dev', company=Company.objects.get(id=485), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Engineering Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=611), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Application Services Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=611), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Technical Support Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=611), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Jr. Spam Data Analyst Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=611), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Jr. Data Scientist Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=611), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineering Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=611), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineering Interns', description='', job_type='Engineering Software', company=Company.objects.get(id=585), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=312), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=571), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='QA Intern', description='', job_type='Engineering QA', company=Company.objects.get(id=571), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Development Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=302), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software/Firmware Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=241), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='CAD Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=241), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Design/Verification Engineer', description='', job_type='Engineering QA', company=Company.objects.get(id=241), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Device/Process Engineer', description='', job_type='Engineering QA', company=Company.objects.get(id=241), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Product/ Product Applications Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=241), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Systems Design Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=241), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Test Development Engineer', description='', job_type='Engineering QA', company=Company.objects.get(id=241), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Industrial & Operations Engineer', description='', job_type='Engineering Hardware', company=Company.objects.get(id=241), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Developer', description='', job_type='Engineering Software', company=Company.objects.get(id=376), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='User Experience', description='', job_type='Engineering Software', company=Company.objects.get(id=376), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Quality Assurance', description='', job_type='Engineering QA', company=Company.objects.get(id=376), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Technical Writer,', description='', job_type='Other', company=Company.objects.get(id=376), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Design Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=583), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Design Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=583), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Applications Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=583), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Applications Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=583), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Product Test Engineer', description='', job_type='Engineering QA', company=Company.objects.get(id=583), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Product Test Intern', description='', job_type='Engineering QA', company=Company.objects.get(id=583), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=583), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=583), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Firmware Engineer', description='', job_type='Engineering QA', company=Company.objects.get(id=583), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Firmware Intern', description='', job_type='Engineering QA', company=Company.objects.get(id=583), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=600), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Technical Program Manager Intern', description='', job_type='Product/Project Management', company=Company.objects.get(id=600), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='User Interface Engineer Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=600), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='UX Design Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=600), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software QA Intern', description='', job_type='Engineering QA', company=Company.objects.get(id=600), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Biomedical, Mechanical, Electrical & Chemical Engineering', description='', job_type='Other', company=Company.objects.get(id=575), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Marketing', description='', job_type='Marketing/PR/Product Mktg', company=Company.objects.get(id=575), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Business', description='', job_type='Business Dev', company=Company.objects.get(id=575), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Communications', description='', job_type='Business Dev', company=Company.objects.get(id=575), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Physics', description='', job_type='Other', company=Company.objects.get(id=575), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Cloud Ops Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=572), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Engineering Operations Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=572), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Field Engineer Intern', description='', job_type='Engineering QA', company=Company.objects.get(id=572), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Product Manager Intern', description='', job_type='Product/Project Management', company=Company.objects.get(id=572), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=572), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer- Frontend Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=572), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Artificial Intelligence (AI) Engineer Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=492), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=576), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer Internship Opportunities', description='', job_type='Engineering Software', company=Company.objects.get(id=470), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Engineering – Software/Firmware Internship', description='', job_type='Engineering Software', company=Company.objects.get(id=619), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern', description='', job_type='Other', company=Company.objects.get(id=592), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Process Engineering - Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=592), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Mechanical Engineering - Intern', description='', job_type='Engineering Hardware', company=Company.objects.get(id=592), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Electrical Engineering - Intern', description='', job_type='Engineering Hardware', company=Company.objects.get(id=592), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Disney Professional Internships', description='', job_type='Other', company=Company.objects.get(id=616), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Multiple engineering internships and Full-time positions available', description='', job_type='Engineering Software', company=Company.objects.get(id=621), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=617), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Technical Degree Sponsor Ship Program.', description='', job_type='Other', company=Company.objects.get(id=574), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Electrical Engineer', description='', job_type='Engineering Hardware', company=Company.objects.get(id=574), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Intern Software Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=586), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Internships', description='', job_type='Other', company=Company.objects.get(id=624), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=610), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineer Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=570), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Research Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=570), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='UX/UI Design Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=570), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Manufacturing Engineer', description='', job_type='Other', company=Company.objects.get(id=594), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Design Engineer', description='', job_type='Engineering Software', company=Company.objects.get(id=594), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Quality Engineer', description='', job_type='Engineering QA', company=Company.objects.get(id=594), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Metallurgist', description='', job_type='Other', company=Company.objects.get(id=594), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Server Software Developer - Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=595), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Mobile Software Developer - Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=595), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Web Software Developer - Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=595), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Sales/Business Development', description='', job_type='Business Dev', company=Company.objects.get(id=609), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Mobile Engineering', description='', job_type='Engineering Software', company=Company.objects.get(id=609), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Engineering', description='', job_type='Engineering Software', company=Company.objects.get(id=609), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Systems Engineering', description='', job_type='Engineering Software', company=Company.objects.get(id=609), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Software Development Internship', description='', job_type='Engineering Software', company=Company.objects.get(id=587), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Ruby on Rails + Javascript Developer', description='', job_type='Engineering Software', company=Company.objects.get(id=587), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='SaaS Application Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=605), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='QA Test Engineer Intern', description='', job_type='Engineering QA', company=Company.objects.get(id=605), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Performance Engineer Intern', description='', job_type='Engineering QA', company=Company.objects.get(id=605), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='TechOps/DevOps Engineer Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=605), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Platform Engineer Intern', description='', job_type='Engineering Software', company=Company.objects.get(id=605), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Project Management Intern', description='', job_type='Product/Project Management', company=Company.objects.get(id=605), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Product Marketing Intern', description='', job_type='Marketing/PR/Product Mktg', company=Company.objects.get(id=605), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Customer Success Intern', description='', job_type='Marketing/PR/Product Mktg', company=Company.objects.get(id=605), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
new_job = Job(name='Business Development Intern', description='', job_type='Business Dev', company=Company.objects.get(id=605), network=Group.objects.get(id=1), fair=Fair.objects.get(id=9))
new_job.save()
